# Generated by Django 5.1.3 on 2025-01-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Inventory',
        ),
    ]
